### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by nanook21** [Arood/directus-extension-media-ai-bundle#1]
I'm trying to use this extension using the "Installing via the npm Registry" option shown here:

https://docs.directus.io/extensions/installing-extensions.html

I have this in my docker-compose.yml:

```
version: "3"
services:
  directus:
    build: 
      context: ./ 
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      AWS_ACCESS_KEY_ID: **VALUE-HERE**
      AWS_SECRET_ACCESS_KEY: **VALUE-HERE**
      AWS_REGION: "us-west-2"
```

And this in Dockerfile:
```
FROM directus/directus:11.0.2

USER root
RUN corepack enable
USER node

RUN pnpm install directus-extension-media-ai-bundle
```

I see this in the logs on load:
`Loaded extensions: directus-extension-media-ai-bundle`

And see the extension in the Extensions tab.

However when I upload images, nothing seems to happen.

Am I missing a step?
